version: 2.1

orbs:
  android: circleci/android@2.0.0
  gradle: circleci/gradle@2.2.0

workflows:
  test-build:
    jobs:
      - android/build:
          executor: { name: android/android-docker, tag: '2022.01.1' }
      - android/run-ui-tests:
          executor: { name: android/android-docker, tag: '2022.01.1' }
      - gradle/run:
          command: ktlint
