version: 2.1

orbs:
  android: circleci/android@2.0.0
  gradle: circleci/gradle@2.2.0

executors:
  android:
    docker:
      - image: cimg/android:2022.04

jobs:
  build:
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Building the debug APK
                command: GRADLE_OPTs="-Xms4g -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process -Dfile.encoding=UTF-8" ./gradlew -s assembleDebug
      - run:
          name: Zipping the debug APK
          command: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'
      - store_artifacts:
          path: ~/project/assemble.zip
  gradle:
    parameters:
      command:
        type: string
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ANDROID_SDK_ROOT=~/android-sdk ./gradlew << parameters.command >> --stacktrace
      - store_artifacts:
          path: ~/project/app/build/reports/tests

workflows:
  test-build:
    jobs:
      - build
      - gradle:
          matrix:
            parameters:
              command: [ 'ktlint', 'test' ]
      - android/run-ui-tests:
          executor: { name: android/android-machine, tag: 2022.04 }
          test-command: ./gradlew connectedAndroidTest
          post-run-tests-steps:
            - store_artifacts:
                path: ~/project/app/build/reports/androidTests/connected/flavors
