version: 2.1

orbs:
  android: circleci/android@2.0.0
  gradle: circleci/gradle@2.2.0

executors:
  android:
    docker:
      - image: cimg/android:2022.01.1

jobs:
  gradle:
    parameters:
      command:
        type: string
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                command: |
                  sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
                  ANDROID_SDK_ROOT=~/android-sdk ./gradlew << parameters.command >> --stacktrace

workflows:
  test-build:
    jobs:
      - gradle:
          matrix:
            parameters:
              command: [ 'ktlint', 'test', 'connectedAndroidTest' ]
      - android/build:
          executor: android
