version: 2.1

orbs:
  android: circleci/android@2.0
  gradle: circleci/gradle@2.2

executors:
  android:
    docker:
      - image: cimg/android:2022.04

jobs:
  build:
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Building the debug APK
                command: ./gradlew -s assembleDebug
      - store_artifacts:
          path: ~/project/build/outputs/apk/debug/app-debug.apk
  lint:
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew ktlint --stacktrace
  test:
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew test --stacktrace
      - store_artifacts:
          path: ~/project/app/build/reports/tests

workflows:
  test-build:
    jobs:
      - build
      - lint
      - test
      - android/run-ui-tests:
          executor: { name: android/android-machine, tag: 2022.04.1 }
          test-command: ./gradlew connectedAndroidTest
          post-run-tests-steps:
            - store_artifacts:
                path: ~/project/app/build/reports/androidTests/connected/flavors
